---
title: "Final Project"
author: "Felicia Cruz"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(here)
library(janitor)
library(lubridate)
library(broom)
```

### Is there a difference in wildfire intensity in Northern California vs Southern California? 

```{r}
# read in dataset from Kaggle 
fires <- read_csv(here("California_Fire_Incidents.csv")) %>% 
  clean_names()

# make a year_started column 
fires$started <- lubridate::as_date(fires$started)
fires <- fires %>% 
  mutate(started_year = lubridate::year(started))

# remove 1969 start years 
fires <- fires %>% 
  filter(started_year != 1969)
```


```{r}
fires$extinguished <- lubridate::as_datetime(fires$extinguished)

# make duration column 

fires <- fires %>% 
  mutate(duration = difftime(extinguished, started, units = c("days")))

  
```


```{r}
fires %>% 
  filter(unique_id != "af8f8070-a3d6-4ca2-8e2b-6da1049a5bea",
         unique_id != "f136ba8d-f6bb-4bad-9815-1d56f9dc8650") %>% 
  ggplot(aes(x = started, y = duration)) +
  geom_point()

```


```{r}
# summary stats of mean acreage burned by started_year 
burned_mean <- fires %>% 
  group_by(started_year) %>% 
  summarize(mean_acres_burned = mean(acres_burned, na.rm=TRUE))
```

```{r}
# establish locations North and South 

fires$north_south <- 0
 
# want 0 if North and 1 for South 
fires$north_south <- replace(fires$north_south,
                             fires$latitude > 36,
                             "North")
fires$north_south <- replace(fires$north_south,
                             fires$north_south == 0,
                             "South")
```

```{r}
# average acres burned by year and north_south -- why ?? I think total acres makes more sense

burned_mean_regions <- fires %>% 
  group_by(started_year, north_south) %>% 
  summarize(mean_acres_burned = mean(acres_burned, na.rm=TRUE))


ggplot(burned_mean_regions, aes(x = started_year, y = mean_acres_burned, color = north_south)) +
  geom_line() +
  labs(title = "Average Acres Burned by Year",
       color = "",
       x = "Year",
       y = "Mean Acres Burned")

# total acres burned by year and region 
acres_by_region <- fires %>% 
  group_by(started_year, north_south) %>% 
  summarize(total_acres = sum(acres_burned, na.rm = TRUE))

ggplot(acres_by_region, aes(x = started_year, y = total_acres, color = north_south)) +
  geom_line() +
  labs(title = "Total Acres Burned by Year",
       color = "",
       x = "Year",
       y = "Acres")
```

```{r}
# scatterplot of all wildfire events 
ggplot(fires, aes(x = started, y = acres_burned, color = north_south)) +
  geom_point(alpha = 0.5) +
  labs(title = "Wildfire Events in California (2013-2019)",
       color = "",
       x = "Started",
       y = "Acres Burned")
```

```{r}
ggplot(fires, aes(x = started, y = acres_burned)) +
  geom_line()
```
```{r}
# Number of fires per year 

year_totals <- fires %>% 
  group_by(started_year) %>% 
  summarize(count = n())


ggplot(year_totals, aes(x = started_year, y = count)) +
  geom_line()
```



# Run a regression 

```{r}
summary(lm(acres_burned ~ started, data = fires))

```

```{r}
# regression for North 

fires_north <- fires %>% 
  filter(north_south == "North")

summary(lm(acres_burned ~ started, data = fires_north))
```

```{r}
# regression for South
fires_south <- fires %>% 
  filter(north_south == "South")

summary(lm(acres_burned ~ started, data = fires_south)) 
```

```{r}
mod <- lm(acres_burned ~ started + north_south + started*north_south, data = fires)
summary(mod)

```

```{r}
ggplot(data = fires, aes(x = started, y = acres_burned, color = north_south)) +
  geom_point(alpha = 0.4) +
  geom_line(data = augment(mod), aes(y = .fitted, color = north_south))

#ggsave("regression_plot.png", width = 5, height = 10)
```

